# Generated by Django 5.0.5 on 2024-05-08 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='series',
            name='episodes',
        ),
        migrations.RemoveField(
            model_name='series',
            name='image',
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('episode_count', models.IntegerField()),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='core.series')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('episode_number', models.IntegerField()),
                ('rating', models.FloatField()),
                ('duration', models.IntegerField()),
                ('genre', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('trailer', models.CharField(max_length=100)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='core.season')),
            ],
        ),
    ]
