# Generated by Django 5.0.5 on 2024-05-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_series_duration_remove_series_episodes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='cast',
            field=models.CharField(default='John Doe, Jane Smith', max_length=100),
        ),
        migrations.AddField(
            model_name='series',
            name='cast',
            field=models.CharField(default='John Doe, Jane Smith', max_length=100),
        ),
        migrations.AddField(
            model_name='series',
            name='image',
            field=models.ImageField(default='images/default_image.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='images/default_image.jpg', upload_to='images/'),
        ),
    ]
